# Generated by Django 4.0.3 on 2022-03-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.CharField(db_index=True, default='Email', max_length=20, verbose_name='Email'),
        ),
    ]
