# Generated by Django 4.0.3 on 2022-03-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Email'),
        ),
    ]
