# Generated by Django 4.0.3 on 2022-03-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_email_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edit',
            field=models.CharField(default=0, max_length=14, verbose_name='edit'),
        ),
    ]
