# Generated by Django 4.0.3 on 2022-03-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edit',
            field=models.CharField(default='edit', max_length=14, verbose_name='edit'),
        ),
    ]
