# Generated by Django 4.0.3 on 2022-03-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(db_index=True, max_length=140, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.CharField(max_length=20, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(db_index=True, default='Anonymous', max_length=14, verbose_name='name'),
        ),
    ]
